kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nas-pvc
---
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: trainer-
spec:
  entrypoint: builder-trainer
  volumes:
    - name: workdir
      persistentVolumeClaim:
        claimName: nas-pvc
    - name: docker
      hostPath:
        path: /var/lib/docker/images/

  templates:
    - name: builder-trainer
      steps:
          - - name: builder
              template: builder
          - - name: submit-trainer-gpu
              template: submit-trainer-gpu

    - name: builder
      container:
        image: 'docker:stable-git'
        command:
          - sh
          - '-c'
        args:
          - >-
            docker login -u TaylorHere
            registry.cn-hangzhou.aliyuncs.com -p Taylor357753 &&
            cd /mnt/vol/ && 
            if cd git/ner; then git 
            pull; else git clone https://github.com/TaylorHere/bi-lstm-crf-ner-tf2.0.git
            git/ner && cd git/ner;
            fi && docker build -t
            registry.cn-hangzhou.aliyuncs.com/taylor/crf:cpu-py3
            . && docker push
            registry.cn-hangzhou.aliyuncs.com/taylor/crf:cpu-py3
        env:
          - name: DOCKER_HOST
            value: 127.0.0.1
        volumeMounts:
          - name: workdir
            mountPath: /mnt/vol
          - name: docker
            mountPath: /var/lib/docker/images/
      sidecars:
        - name: dind
          image: 'docker:18.09.4-dind'
          securityContext:
            privileged: true
          mirrorVolumeMounts: true

    - name: submit-trainer-gpu
      resource:                   # indicates that this is a resource template
        action: create            # can be any kubectl action (e.g. create, delete, apply, patch)
        # The successCondition and failureCondition are optional expressions.
        # If failureCondition is true, the step is considered failed.
        # If successCondition is true, the step is considered successful.
        # They use kubernetes label selection syntax and can be applied against any field
        # of the resource (not just labels). Multiple AND conditions can be represented by comma
        # delimited expressions.
        # For more details: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
        successCondition: status.succeeded > 0
        failureCondition: status.failed > 0
        manifest: |               #put your kubernetes spec here
            apiVersion: batch/v1
            kind: Job
            metadata:
                generateName: trainer-job-
                ownerReferences:
                - apiVersion: argoproj.io/v1alpha1
                  blockOwnerDeletion: true
                  kind: Workflow
                  name: "{{workflow.name}}"
                  uid: "{{workflow.uid}}"
            spec:
              template:
                metadata:
                  annotations:
                    k8s.aliyun.com/eci-gpu-type : "T4"
                  name: trainer-job
                spec:
                  restartPolicy: Never
                  volumes:
                    - name: workdir
                      persistentVolumeClaim:
                        claimName: nas-pvc
                  containers:
                  - name: trainer-job
                    imagePullPolicy: IfNotPresent
                    resources:
                      limits:
                          nvidia.com/gpu:  1
                    image: registry.cn-hangzhou.aliyuncs.com/taylor/crf:cpu-py3
                    command:
                      - python
                      - train.py
                    volumeMounts:
                      - name: workdir
                        mountPath: /home/jovyan/shared/