name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Docker Publish
      uses: manusa/actions-publish-docker@v1.0.1
      with:
        name: taylor/crf
        tag: latest
        username: TaylorHere
        password: Taylor357753
        registry: registry.cn-hangzhou.aliyuncs.com
