name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Publish Docker
      uses: elgohr/Publish-Docker-Github-Action@2.12
      with:
        name: taylor/crf:${{ GITHUB_SHA }}
        username: TaylorHere
        password: Taylor357753
        registry: registry.cn-hangzhou.aliyuncs.com
